//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Offered = new HashSet<Offered>();
            this.Task_Status = new HashSet<Task_Status>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public System.DateTime createdat { get; set; }
        public string category { get; set; }
        public int cost { get; set; }
        public int clientID { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<System.DateTime> duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offered> Offered { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Status> Task_Status { get; set; }
        public virtual Task_Status Task_Status1 { get; set; }
        public virtual User User { get; set; }
    }
}
